export const MESSAGE_SUCCESS = 'message_success'
export const MESSAGE_WARNING = 'message_warning'
export const MESSAGE_ERROR = 'message_error'
export const MESSAGE_INFO = 'message_info'
export const MESSAGEN = 'messagen'
export const GOTO = 'goto'
export const REFRESH = 'refresh'
export const POPUP = 'popup'